logging:
  file:
    path:
      logs/
    name:
      logs/application.log
debug:
  true
trace:
  true
spring:
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://213.171.4.235:5432/documentapp_db
    username: db_admin
    password: wHO0mmBM
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: document.app.help@gmail.com
    password: evwgtekpttyzqyuy

    port: 587
    protocol: smtp
    properties:
        "mail.transport.protocol": smtp
        "mail.smtp.auth": true
        "mail.smtp.starttls.enable": true
