spring:
  datasource:
    hikari:
      auto-commit: true
    url: jdbc:postgresql://213.171.4.235:5432/documentapp_db
    username: db_admin
    password: wHO0mmBM

    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
