spring:
  datasource:
    url: jdbc:postgresql://213.171.4.235:5432/documentapp_db
    username: db_admin
    password: wHO0mmBM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
